#!/usr/bin/bash
VER="3.3.5"
build_date=$(date +"%Y-%m-%d")
CHATID="-1001802548906"
TOKEN="6877892509:AAG7xeKonLHrStTdoPmISZH_68U1JH_ZO7E"

send_file() {
    curl -F chat_id=${CHATID} -F document=@"$1" -F caption="$2" "https://api.telegram.org/bot${TOKEN}/sendDocument"
}

# Update source
rm -rf source
git clone https://github.com/eraselk/ngentouch-module source
cd source
    echo
    echo "[~] Zipping.."
    zip -r9 "NgenTouch_${VER}_${build_date}.zip" * -x README.md .git update.json *build 
    echo
    echo "[√] DONE"
    echo

    # Upload to Telegram
    echo "[~] UPLOAD to TG"
    send_file "NgenTouch_${VER}_${build_date}.zip" "Version: ${VER} || Build Date: ${build_date}"1
exit 0
