#!/system/bin/sh
VER="3.3.5"
build_date=$(date +"%Y-%m-%d")
CHATID="-1001802548906"
TOKEN="6877892509:AAG7xeKonLHrStTdoPmISZH_68U1JH_ZO7E"

function send_file() {
curl -F chat_id=${CHATID} -F document=@$1 -F caption="$2" "https://api.telegram.org/bot${TOKEN}/sendDocument"
}

(
    clear
    sleep 3s
    echo
    echo "[~] Zipping.."
    zip -r9 ../NgenTouch_${VER}_${build_date}.zip * -x README.md .git update.json *build
    cd ..
    echo
    echo "[âˆš] DONE"
    echo
) > build_mod.log 2>&1

# Upload to Telegram
clear
echo "[~] UPLOAD to TG"
send_file NgenTouch_${VER}_${build_date}.zip "Version: ${VER} || Build Date: ${build_date}"
send_file build_mod.log "Build Log"

